#pragma once
// Auto-generated by dump_all_offsets.py — 2026-09-04T15:21:47
// Full catalog: static path migrate + live validation PASS required.

#if defined(OAK_REQUIRE_PROTECTION)
#define OAK_RUNTIME_OFFSET(name, developmentValue) inline uintptr_t name = developmentValue
#else
#define OAK_RUNTIME_OFFSET(name, developmentValue) inline uintptr_t name = developmentValue
#endif

namespace oak_offsets {
namespace modbase {
    OAK_RUNTIME_OFFSET(FOV_Context, 0x1007C70);
    OAK_RUNTIME_OFFSET(FovBase, 0x9C4);
    OAK_RUNTIME_OFFSET(Network, 0x100EB60);
    OAK_RUNTIME_OFFSET(NetworkManager, 0x100EBD0);
    OAK_RUNTIME_OFFSET(PhysicsWorld, 0x42662E0);
    OAK_RUNTIME_OFFSET(ScopeFovCtx, 0x42638B0);
    OAK_RUNTIME_OFFSET(Tick, 0xFF3928);
    OAK_RUNTIME_OFFSET(World, 0x4262FE8);
}
namespace world {
    OAK_RUNTIME_OFFSET(BulletCount, 0xE08);
    OAK_RUNTIME_OFFSET(BulletList, 0xE00);
    OAK_RUNTIME_OFFSET(Camera, 0x1B8);
    OAK_RUNTIME_OFFSET(Day, 0x2974);
    OAK_RUNTIME_OFFSET(DayTime, 0x2978);
    OAK_RUNTIME_OFFSET(EyeAccom, 0x296C);
    OAK_RUNTIME_OFFSET(FarEntList, 0x1090);
    OAK_RUNTIME_OFFSET(FarTableSize, 0x1098);
    OAK_RUNTIME_OFFSET(GrassOffline, 0xBF0);
    OAK_RUNTIME_OFFSET(Hour, 0x2970);
    OAK_RUNTIME_OFFSET(ItemList, 0x2060);
    OAK_RUNTIME_OFFSET(ItemListSize, 0x2068);
    OAK_RUNTIME_OFFSET(LocalPlayer, 0x2960);
    OAK_RUNTIME_OFFSET(NearEntList, 0xF48);
    OAK_RUNTIME_OFFSET(NoGrass, 0xC00);
    OAK_RUNTIME_OFFSET(PlayerOn, 0x2968);
    OAK_RUNTIME_OFFSET(SlowEntList, 0x2010);
    OAK_RUNTIME_OFFSET(SlowEntValidCount, 0x1F90);
    OAK_RUNTIME_OFFSET(SlowTableSize, 0x2018);
    OAK_RUNTIME_OFFSET(WeatherController, 0x7198);
}
namespace camera {
    OAK_RUNTIME_OFFSET(GetProjectionD1, 0xD0);
    OAK_RUNTIME_OFFSET(GetProjectionD2, 0xDC);
    OAK_RUNTIME_OFFSET(InvertedViewForward, 0x20);
    OAK_RUNTIME_OFFSET(InvertedViewRight, 0x8);
    OAK_RUNTIME_OFFSET(InvertedViewTranslation, 0x2C);
    OAK_RUNTIME_OFFSET(InvertedViewUp, 0x14);
    OAK_RUNTIME_OFFSET(ViewPortSize, 0x58);
}
namespace entity {
    OAK_RUNTIME_OFFSET(FutureVisualState, 0x120);
    OAK_RUNTIME_OFFSET(IsDead, 0xE2);
    OAK_RUNTIME_OFFSET(NetworkId, 0x6DC);
    OAK_RUNTIME_OFFSET(NetworkIdPlayer, 0x6E4);
    OAK_RUNTIME_OFFSET(Stamina, 0x6A4);
    OAK_RUNTIME_OFFSET(Type, 0x180);
    OAK_RUNTIME_OFFSET(VisualState, 0x1C8);
}
namespace inventory {
    OAK_RUNTIME_OFFSET(Hands, 0x1B0);
}
namespace player {
    OAK_RUNTIME_OFFSET(DamageManager, 0x188);
    OAK_RUNTIME_OFFSET(InputController, 0x7E8);
    OAK_RUNTIME_OFFSET(Inventory, 0x650);
    OAK_RUNTIME_OFFSET(RecordValue, 0x2C);
    OAK_RUNTIME_OFFSET(Skeleton, 0x7E0);
    OAK_RUNTIME_OFFSET(StatsContainer, 0x6F0);
}
namespace network {
    OAK_RUNTIME_OFFSET(IdentityCount, 0x1C);
    OAK_RUNTIME_OFFSET(ManagerNetworkClient, 0x50);
    OAK_RUNTIME_OFFSET(PlayerName, 0xF8);
    OAK_RUNTIME_OFFSET(ScoreboardPtr, 0x18);
    OAK_RUNTIME_OFFSET(ScoreboardSize, 0x24);
    OAK_RUNTIME_OFFSET(ThirdPersonFlag, 0x9C);
}
namespace scoreboard_identity {
    OAK_RUNTIME_OFFSET(Name, 0xF8);
    OAK_RUNTIME_OFFSET(NetworkId, 0x30);
    OAK_RUNTIME_OFFSET(SteamId, 0xA0);
}
namespace player_identity {
    OAK_RUNTIME_OFFSET(Name, 0xB0);
}
namespace entity_owner {
    OAK_RUNTIME_OFFSET(Owner, 0xA0);
}
namespace infected {
    OAK_RUNTIME_OFFSET(Skeleton, 0x670);
}
namespace entitytype {
    OAK_RUNTIME_OFFSET(ConfigName, 0xD0);
    OAK_RUNTIME_OFFSET(ModelName, 0xB0);
    OAK_RUNTIME_OFFSET(TypeName, 0x98);
}
namespace anim {
    OAK_RUNTIME_OFFSET(AnimComponent, 0x118);
    OAK_RUNTIME_OFFSET(MatrixArray, 0xBE8);
    OAK_RUNTIME_OFFSET(MatrixB, 0x54);
}
namespace skeleton {
    OAK_RUNTIME_OFFSET(AnimClass1, 0x98);
    OAK_RUNTIME_OFFSET(AnimClass2, 0x28);
    OAK_RUNTIME_OFFSET(AnimComponent, 0x118);
}
}

#undef OAK_RUNTIME_OFFSET
